tap "homebrew/bundle"
tap "homebrew/core"
tap "caskroom/cask"

brew "git"
brew "tmux"
brew "vim"
brew "gpg"
brew "pinentry-mac"
brew "git-secret"
brew "stow"
brew "antigen"
brew "hub"
brew "kubectl"
brew "direnv"
brew "neovim"
brew "autojump"
brew "leiningen"
brew "ssh-copy-id"
brew "tree"
brew "npm"
brew "pv"
brew "sshuttle"
brew "ansible"
brew "httpie"
brew "coreutils"
brew "tig"
brew "jq"
brew "emacs"
brew "go"
brew "watch"
brew "zsh"
brew "docker-machine-driver-xhyve"

cask "java" unless system "/usr/libexec/java_home --failfast"
cask "google-chrome"
cask "visual-studio-code"
cask "iterm2"
cask "meld"
cask "minikube"

